import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import {validateRequest} from "@/lib/validate-req";
import {logout} from "@/app/components/actions";
import Link from "next/link";
import {Avatar, Badge, Box, Button, Card, Flex, Theme} from "@radix-ui/themes";
import '@radix-ui/themes/styles.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function Loginout() {
  const {user} = await validateRequest();

  return (
      <Card className="w-screen	">

      <Flex gap="2" className="pt-3">

        <span>{user &&
            <form action={logout}>

                <Box maxWidth="240px">
                        <Flex gap="3" align="center">
                            <Avatar
                                size="2"
                                radius="full"
                                fallback="P"
                                alt="profile picture"
                            />
                            <Box>
                                <div>
                                   {user.username}
                                </div>

                            </Box>
                            <Button color="crimson" variant="soft" size="1" className="self-end justify-end	ml-10	" >
                                logout</Button>
                        </Flex>
                </Box>
            </form>
        }
        </span>
          <span >{!user &&   <Button color="cyan" variant="soft">
              <Link href="/">login</Link></Button>}</span>
        <span >{!user && <Button color="gray" variant="outline" highContrast>
            <Link href="/">signup</Link></Button>}</span>
      </Flex>
      </Card>

  );
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <Theme appearance="dark" radius="full" scaling="110%">

      <Loginout/>

      {children}
      </Theme>

      </body>
      </html>
  );
}
