import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {validateRequest} from "@/lib/validate-req";
import {logout} from "@/app/components/actions";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function Loginout() {
  const {user} = await validateRequest();

  return (
      <>
        <span>{user &&
            <form action={logout}>
                <button>logout</button>
                <span className="m-2">Hello! :{user.username}</span>
            </form>
        }
        </span>
        <span className="p-2 mt-5 pt-6">{!user && <Link href="/login">login</Link>}</span>
        <span className="p-2 mt-5 pt-6">{!user && <Link href="/signup">signUP</Link>}</span>
      </>
  );
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">

      <body className={inter.className}>
      <Loginout/>
      {children}
      </body>
      </html>
  );
}
